# site settings

title: gerrykou
description: Jekyll theme for a beautiful online CV
taglong: 
tagshort: 
url: https://cvless.netlify.app
baseurl: ""
permalink: pretty
repo: https://github.com/gerrykou/gerrykou.github.io

# author settings

author:
  name: Gerry
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: gerrykou
  linkedin: kounadisgerasimos

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
